import type { Metadata } from "next";
import { Poppins, Young_Serif , Allison } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900']
});

const youngSerif = Young_Serif({
  variable: "--font-young-serif",
  subsets: ["latin"],
  weight: ['400'],
});

const allison = Allison({
  variable: "--font-allison",
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${youngSerif.variable} ${allison.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
